#!/bin/bash

echo "Starting Chat Bot service"
systemctl daemon-reload
systemctl enable wlanpi-chat-bot
systemctl start wlanpi-chat-bot

echo ""
echo "Enter your API key:"
echo "sudo nano /opt/wlanpi-chat-bot/etc/config.json"
