#!/bin/bash

# Enable SPI interface for OLED display
#echo "Enabling SPI interface"
#if grep -q -E "^?dtparam=spi=" /boot/config.txt; then
#	sed -i 's/^#\?dtparam=spi=.*/dtparam=spi=on/' /boot/config.txt
#else
#	echo "dtparam=spi=on" >> /boot/config.txt
#fi

