name: Deploy to Packagecloud

on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'debian/changelog'

jobs:
  sbuild:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}

    runs-on: 'ubuntu-20.04'

    strategy:
      fail-fast: false
      matrix:
        distro: [bullseye]
        arch: [armhf,arm64]

    environment: PACKAGECLOUD

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sbuild for ${{ matrix.distro }} ${{ matrix.arch }}
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Archive artifacts and upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-chat-bot-${{ matrix.distro }}-${{ matrix.arch }}
          path: ${{ steps.build-debian-package.outputs.deb-package }}

      - name: Upload package to packagecloud
        uses: danielmundi/upload-packagecloud@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          packagecloud-username: wlanpi
          packagecloud-repo: dev
          packagecloud-distrib: raspbian/${{ matrix.distro }}
          packagecloud-token: ${{ secrets.PACKAGECLOUD_TOKEN }}
  
  slack-workflow-status:
    if: always()
    name: Post Workflow Status to Slack
    needs:
      - sbuild
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
